#!/usr/bin/env bash

# path:       /usr/bin/startinstawm
# author:     The-Repo-Club [wayne6324@gmail.com]
# github:     https://github.com/The-Repo-Club/instawm
# date:       2021-04-10 12:34:47.440579

while true; do
    # Log stderror to a file 
    #instawm 2> ~/.instawm.log
    # No error logging
    instawm >/dev/null 2>&1
done