static const char black[]       = "#21222C";
static const char gray1[]       = "#CCCCCC";
static const char gray2[]       = "#283036"; // unfocused window border
static const char gray3[]       = "#434C5E";
static const char gray4[]       = "#283036";
static const char blue[]        = "#59FFF9";  // focused window border
static const char green[]       = "#59FF59";
static const char red[]         = "#FF5959";
static const char orange[]      = "#FF9C59";
static const char yellow[]      = "#FFFF59";
static const char pink[]        = "#FF59f9";
static const char col_borderbar[]  = "#21222C"; // inner border
